[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "python-telegram-bot>=22.4",
    "pytz>=2025.2",
    "requests>=2.32.5",
    "schedule>=1.2.2",
    "selenium>=4.35.0",
    "streamlit>=1.49.1",
    "trafilatura>=2.0.0",
]
